import { TABLE_ROUTES } from "./serve.js";
import type { OpenApiDocument } from "./contract-test.js";

export interface K6ExportOptions {
  baseUrl: string;
  vus?: number;
  durationSeconds?: number;
  apiKey?: string;
  /**
   * If given, generate requests from this real OpenAPI contract's
   * declared GET operations instead of eco-faker's own fixed
   * TABLE_ROUTES -- for load-testing an arbitrary real API matching this
   * contract (the same contract `test --contract` validates against),
   * not just eco-faker's own mock.
   */
  contract?: OpenApiDocument;
}

interface RoutePair {
  /** The "list" path, no path params, e.g. `/api/orders`. */
  listPath: string;
  /** The "get by id" path template, e.g. `/api/orders/{id}` -- undefined if no such sibling operation exists in the contract/route set. */
  detailPathTemplate?: string;
  label: string;
}

function routePairsFromTableRoutes(): RoutePair[] {
  return Object.keys(TABLE_ROUTES)
    .sort()
    .map((route) => ({ listPath: `/api/${route}`, detailPathTemplate: `/api/${route}/{id}`, label: route }));
}

/**
 * Derives list/detail route pairs from a real OpenAPI contract.
 *
 * Scope, stated plainly: only paths with NO path parameters at all are
 * treated as "list" entry points (a real, common shape -- `/api/orders`,
 * `/users`), and a sibling is looked for by appending `/{something}` to
 * that same path (matching whatever single path-param name the contract
 * actually declares, not assumed to be `id`). Paths with more than one
 * path parameter, or a path parameter that ISN'T preceded by a plain
 * list-style parent, are not attempted -- resolving an arbitrary path
 * param's real value from an OpenAPI spec's own declared examples (which
 * may not exist at all) is a substantially bigger problem than this
 * first slice takes on. A k6 script only using real ids discovered live
 * from a real list response (the same dynamic-discovery approach used
 * for TABLE_ROUTES) is what's built here, not a general OpenAPI-to-k6
 * path-parameter resolver.
 */
function routePairsFromContract(contract: OpenApiDocument): RoutePair[] {
  const paths = Object.keys(contract.paths ?? {});
  const listPaths = paths.filter((p) => !p.includes("{") && (contract.paths?.[p]?.get ?? null) !== null);
  const pairs: RoutePair[] = [];
  for (const listPath of listPaths) {
    const detailCandidate = paths.find((p) => {
      const withoutParam = p.replace(/\/\{[^}]+\}$/, "");
      return withoutParam === listPath && p !== listPath && /\{[^}]+\}$/.test(p) && contract.paths?.[p]?.get;
    });
    pairs.push({ listPath, detailPathTemplate: detailCandidate, label: listPath.replace(/^\/+/, "").replace(/\//g, "-") || "root" });
  }
  return pairs;
}

/**
 * Generates a real, runnable k6 (https://k6.io/) script. Every VU-
 * iteration exercises every route pair once: a GET on the list path,
 * then -- if a detail path template exists -- extracts a real id from
 * the list response's first row and GETs the detail path with it
 * substituted in, checking the real HTTP status at each step. This is
 * the same "discover a real id live from a real response, don't assume
 * one" approach `test --scenario`'s `{{step.field}}` captures use,
 * necessarily reimplemented in k6's own script language (k6 scripts run
 * standalone, outside this project's own request-running code) rather
 * than shared code -- there's no way to share a TS module directly with
 * a k6 script's execution environment.
 */
export function buildK6Script(options: K6ExportOptions): string {
  const vus = options.vus ?? 10;
  const duration = options.durationSeconds ?? 30;
  const pairs = options.contract ? routePairsFromContract(options.contract) : routePairsFromTableRoutes();

  const headerLine = options.apiKey
    ? `  const params = { headers: { Authorization: 'Bearer ${options.apiKey}' } };`
    : `  const params = {};`;

  const routeBlocks = pairs
    .map((pair) => {
      const detailBlock = pair.detailPathTemplate
        ? `
    const body = safeJson(listRes);
    const firstId = body && Array.isArray(body.data) && body.data.length > 0 ? body.data[0].id : undefined;
    if (firstId !== undefined) {
      const detailRes = http.get(\`\${BASE_URL}${pair.detailPathTemplate.replace(/\{[^}]+\}/, "")}\${firstId}\`, params);
      check(detailRes, { '${pair.label}: detail status is 2xx': (r) => r.status >= 200 && r.status < 300 });
    }`
        : "";
      return `
  {
    const listRes = http.get(\`\${BASE_URL}${pair.listPath}\`, params);
    check(listRes, { '${pair.label}: list status is 2xx': (r) => r.status >= 200 && r.status < 300 });${detailBlock}
  }`;
    })
    .join("\n");

  return `import http from 'k6/http';
import { check, sleep } from 'k6';

// Generated by eco-faker's \`k6-export\`. ${
    options.contract
      ? "Routes derived from the given OpenAPI contract's declared GET operations."
      : "Routes are eco-faker's own real TABLE_ROUTES (the exact list `serve`/the Postman export use -- never a second, hand-typed copy)."
  }
export const options = {
  vus: ${vus},
  duration: '${duration}s',
};

const BASE_URL = __ENV.BASE_URL || '${options.baseUrl}';

function safeJson(res) {
  try {
    return res.json();
  } catch (e) {
    return null;
  }
}

export default function () {
${headerLine}
${routeBlocks}

  sleep(1);
}
`;
}
