import type { SchemaMapping } from "./introspect/mapper.js";
import { buildEcoSeedScript } from "./scaffold.js";

/**
 * The six core relational tables -- the ones `generate()` always produces
 * regardless of which optional feature flags (recommendation data,
 * support tickets, inventory simulation, ...) are on, and the ones the
 * README's own Quick Start describes as the baseline dataset. Scoped
 * deliberately to just these six rather than all ~20 tables `generate()`
 * can produce -- the rest are optional depending on config, and a seed
 * script that unconditionally tries to insert into tables that may not
 * exist in this particular dataset would be the wrong default.
 *
 * Order matters: this is the real FK-dependency order (a cart references
 * a user, an order references a cart, a shipment references an order,
 * ...), verified in tests/orm-scaffold.test.ts against the *actual*
 * CREATE TABLE order `output/sql.ts` emits for these same six tables --
 * not just asserted to match by inspection, so a future reordering there
 * doesn't silently make this list wrong.
 */
export const CORE_TABLES = ["users", "carts", "abandoned_checkouts", "orders", "shipments", "return_requests"] as const;
export type CoreTable = (typeof CORE_TABLES)[number];

/** users -> users, abandoned_checkouts -> abandonedCheckouts -- the real property name generate()'s JSON output uses for this canonical table. */
export function tableToCamel(tableName: string): string {
  return tableName.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** first_name -> firstName, abandonment_timeout_hours -> abandonmentTimeoutHours -- the real property name on each record in generate()'s JSON output. Canonical columns are always snake_case (see mapper.ts's CANONICAL_COLUMNS) specifically so this conversion is this mechanical; there's no separate name registry to keep in sync. */
export function columnToCamel(columnName: string): string {
  return columnName.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

export interface OrmScaffoldFile {
  path: string;
  contents: string;
}

export interface OrmScaffoldResult {
  files: OrmScaffoldFile[];
  nextSteps: string[];
  /** Core tables with no confident target model in the given schema -- skipped entirely in the generated seed script rather than guessed at. */
  skippedTables: string[];
}

function mappedTables(mapping: SchemaMapping): { table: CoreTable; targetModel: string; columns: { canonical: string; target: string }[] }[] {
  const result: { table: CoreTable; targetModel: string; columns: { canonical: string; target: string }[] }[] = [];
  for (const table of CORE_TABLES) {
    const entry = mapping[table];
    if (!entry || !entry.targetModel) continue;
    const columns = Object.entries(entry.columns).map(([canonical, m]) => ({ canonical, target: m.targetColumn }));
    result.push({ table, targetModel: entry.targetModel, columns });
  }
  return result;
}

function skippedTables(mapping: SchemaMapping): string[] {
  return CORE_TABLES.filter((t) => !mapping[t]?.targetModel);
}

/**
 * Prisma's `createMany` takes plain scalar values per row -- our own
 * canonical foreign-key columns (`user_id`, `cart_id`, ...) are already
 * plain string ids in the generated JSON, exactly what `createMany`
 * expects, so no relation `connect`/nested-create handling is needed here.
 * Complex fields (`items`, `address`, `events`, ...) are passed through as
 * real JS objects/arrays, matching a Prisma `Json` column; if the target
 * column is a plain string/text type instead, wrap the value in
 * `JSON.stringify(...)` in the generated file before running it.
 */
export function buildPrismaSeedScript(mapping: SchemaMapping, seed: number): OrmScaffoldResult {
  const tables = mappedTables(mapping);

  const createManyBlocks = tables
    .map(({ table, targetModel, columns }) => {
      const camelTable = tableToCamel(table);
      const camelModel = targetModel.charAt(0).toLowerCase() + targetModel.slice(1);
      const fieldLines = columns.map(({ canonical, target }) => `      ${target}: row.${columnToCamel(canonical)},`).join("\n");
      return `  await prisma.${camelModel}.createMany({
    data: dataset.${camelTable}.map((row) => ({
${fieldLines}
    })),
  });
  console.log(\`Inserted \${dataset.${camelTable}.length} ${camelTable} via ${targetModel}.createMany\`);`;
    })
    .join("\n\n");

  const contents = `// Generated by \`my-eco-gen init prisma\`. Run: npx tsx prisma/seed.ts
// (or wire into Prisma's own seed convention: add "prisma": { "seed": "tsx prisma/seed.ts" }
// to package.json, then \`npx prisma db seed\`.)
//
// Reads ./eco-data.json (see scripts/eco-seed.mjs) and inserts it via
// PrismaClient, using the column mapping in ./mapping.json -- review that
// file before trusting it, especially any column with confidence 0.
import { PrismaClient } from "@prisma/client";
import { readFileSync } from "node:fs";
import path from "node:path";

const prisma = new PrismaClient();

async function main() {
  const dataset = JSON.parse(readFileSync(path.join(process.cwd(), "eco-data.json"), "utf-8"));

${createManyBlocks}
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
`;

  return {
    files: [
      { path: "scripts/eco-seed.mjs", contents: buildEcoSeedScript(seed) },
      { path: "prisma/seed.ts", contents },
    ],
    nextSteps: [
      "Next steps:",
      "  1. npm install eco-faker @prisma/client   (if not already installed)",
      "  2. Make sure DATABASE_URL is set and `npx prisma generate` has run against your real schema",
      "  3. node scripts/eco-seed.mjs   -- writes eco-data.json",
      "  4. npx tsx prisma/seed.ts",
      "",
      "Review mapping.json before trusting it -- any column with confidence 0 had no confident match in your schema and fell back to its canonical name, which may not be a real field on your model.",
    ],
    skippedTables: skippedTables(mapping),
  };
}

/**
 * Drizzle's actual runtime connection setup (which driver -- postgres-js,
 * node-postgres, better-sqlite3, neon, ...) can't be inferred from parsing
 * schema field names alone, so this is a template with the connection
 * left as an explicit fill-in, not a script that runs unmodified the way
 * the Prisma one does. Stated plainly rather than guessed at.
 */
export function buildDrizzleSeedScript(mapping: SchemaMapping, seed: number): OrmScaffoldResult {
  const tables = mappedTables(mapping);

  const insertBlocks = tables
    .map(({ table, targetModel, columns }) => {
      const camelTable = tableToCamel(table);
      const fieldLines = columns.map(({ canonical, target }) => `    ${target}: row.${columnToCamel(canonical)},`).join("\n");
      return `  await db.insert(schema.${targetModel}).values(
    dataset.${camelTable}.map((row) => ({
${fieldLines}
    }))
  );
  console.log(\`Inserted \${dataset.${camelTable}.length} ${camelTable} into ${targetModel}\`);`;
    })
    .join("\n\n");

  const contents = `// Generated by \`my-eco-gen init drizzle\`. Fill in the TODO below, then:
// Run: npx tsx scripts/eco-seed-drizzle.ts
//
// Reads ./eco-data.json (see scripts/eco-seed.mjs) and inserts it via your
// own Drizzle \`db\` instance, using the column mapping in ./mapping.json --
// review that file before trusting it, especially any column with
// confidence 0.
import { readFileSync } from "node:fs";
import path from "node:path";
import * as schema from "./schema.js"; // TODO: point this at your real Drizzle schema module

// TODO: replace with your project's real Drizzle connection. Examples:
//   import { drizzle } from "drizzle-orm/postgres-js";
//   import postgres from "postgres";
//   const db = drizzle(postgres(process.env.DATABASE_URL!), { schema });
const db = /* TODO */ undefined as unknown as { insert: (table: unknown) => { values: (rows: unknown[]) => Promise<unknown> } };

async function main() {
  const dataset = JSON.parse(readFileSync(path.join(process.cwd(), "eco-data.json"), "utf-8"));

${insertBlocks}
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`;

  return {
    files: [
      { path: "scripts/eco-seed.mjs", contents: buildEcoSeedScript(seed) },
      { path: "scripts/eco-seed-drizzle.ts", contents },
    ],
    nextSteps: [
      "Next steps:",
      "  1. npm install eco-faker   (if not already installed)",
      "  2. Edit scripts/eco-seed-drizzle.ts: fix the schema import and fill in your real db connection (marked TODO)",
      "  3. node scripts/eco-seed.mjs   -- writes eco-data.json",
      "  4. npx tsx scripts/eco-seed-drizzle.ts",
      "",
      "This one's a template, not a drop-in script -- Drizzle's connection setup (driver, credentials) varies too much project-to-project to generate blindly.",
      "Review mapping.json before trusting it -- any column with confidence 0 had no confident match in your schema.",
    ],
    skippedTables: skippedTables(mapping),
  };
}

/**
 * SQLAlchemy is Python, and eco-faker has no Python bindings (it's an npm
 * package only) -- so unlike the two TypeScript targets above, this seed
 * script can't call `generate()` in-process. It shells out to the real
 * CLI to produce eco-data.json (via the same scripts/eco-seed.mjs this
 * scaffold already writes), then reads that JSON from Python. Same
 * "connection setup varies too much to infer" reasoning as Drizzle above
 * applies here too -- the SQLAlchemy Session/engine is left as a fill-in.
 */
export function buildSqlAlchemySeedScript(mapping: SchemaMapping, seed: number): OrmScaffoldResult {
  const tables = mappedTables(mapping);

  const insertBlocks = tables
    .map(({ table, targetModel, columns }) => {
      const camelTable = tableToCamel(table);
      const fieldLines = columns.map(({ canonical, target }) => `            ${target}=row["${columnToCamel(canonical)}"],`).join("\n");
      return `    rows = dataset["${camelTable}"]
    session.add_all([
        ${targetModel}(
${fieldLines}
        )
        for row in rows
    ])
    print(f"Inserted {len(rows)} ${camelTable} into ${targetModel}")`;
    })
    .join("\n\n");

  const contents = `# Generated by \`my-eco-gen init sqlalchemy\`. Fill in the TODO below, then:
# Run: python seed.py
#
# eco-faker has no Python bindings -- this shells out to the real CLI
# (via node, same as scripts/eco-seed.mjs) to produce eco-data.json, then
# reads that JSON here. Uses the column mapping in ./mapping.json -- review
# that file before trusting it, especially any column with confidence 0.
import json
import subprocess
from pathlib import Path

# TODO: replace with your project's real SQLAlchemy engine/session setup. Example:
#   from sqlalchemy import create_engine
#   from sqlalchemy.orm import Session
#   engine = create_engine("postgresql://user:pass@localhost/db")
#   session = Session(engine)
from models import ${[...new Set(tables.map((t) => t.targetModel))].join(", ")}  # TODO: point this at your real models module

def main():
    subprocess.run(["node", "scripts/eco-seed.mjs"], check=True)
    dataset = json.loads(Path("eco-data.json").read_text())

${insertBlocks}

    session.commit()

if __name__ == "__main__":
    main()
`;

  return {
    files: [
      { path: "scripts/eco-seed.mjs", contents: buildEcoSeedScript(seed) },
      { path: "seed.py", contents },
    ],
    nextSteps: [
      "Next steps:",
      "  1. npm install eco-faker   (if not already installed -- scripts/eco-seed.mjs needs it)",
      "  2. Edit seed.py: fill in your real SQLAlchemy engine/session and models import (marked TODO)",
      "  3. python seed.py   -- runs scripts/eco-seed.mjs for you, then inserts the result",
      "",
      "This one's a template, not a drop-in script -- eco-faker has no Python bindings, and your database connection setup can't be inferred from the schema alone.",
      "Review mapping.json before trusting it -- any column with confidence 0 had no confident match in your schema.",
    ],
    skippedTables: skippedTables(mapping),
  };
}
